import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import '../domain/question.dart';
import '../domain/question_enums.dart';

/// Supplies the content a fresh install starts with.
///
/// Injectable so [QuestionRepository.ensureSeeded] can be tested without an
/// asset bundle.
typedef QuestionPackLoader = Future<List<Question>> Function();

/// Content packs bundled in the APK.
///
/// A pack is a JSON file of questions authored ahead of time — written by hand
/// or generated by `tools/content/generate.mjs`, validated there, and reviewed
/// before it ships. Every install gets the whole corpus offline on first
/// launch, at no runtime cost and against no quota.
///
/// This replaced a hand-maintained Dart list. The reason is not aesthetics:
/// content in Dart source cannot be written by a tool, cannot be validated in
/// CI without compiling the app, and is compiled into the binary uncompressed.
/// A JSON asset is scriptable, checkable, and compressed inside the APK.
///
/// Packs are discovered rather than named, so adding one is dropping a file
/// into `assets/content/`. Ordering is by filename so seeding is deterministic.
abstract final class QuestionPack {
  static const directory = 'assets/content/';
  static const _filePrefix = '${directory}pack-';

  /// Loads and parses every bundled pack.
  ///
  /// Bundled content is stamped [QuestionSource.seed]: it ships in the APK, so
  /// it is available offline, before sign-in, and before any AI request. Packs
  /// synced from Firestore later are [QuestionSource.curated] instead, which
  /// is what lets generated and downloaded content be purged separately.
  static Future<List<Question>> loadBundled({AssetBundle? bundle}) async {
    final assets = bundle ?? rootBundle;
    final manifest = await AssetManifest.loadFromAssetBundle(assets);

    final paths =
        manifest
            .listAssets()
            .where((p) => p.startsWith(_filePrefix) && p.endsWith('.json'))
            .toList()
          ..sort();

    final questions = <Question>[];
    final seenIds = <String>{};

    for (final path in paths) {
      final raw = await assets.loadString(path);

      // Parsed off the main isolate. It happens once, on first launch, but a
      // corpus in the thousands is enough JSON to drop frames on the way in,
      // and the feed is building its first screen at exactly that moment.
      final entries = await compute(_decodePack, raw);

      for (final entry in entries) {
        final question = Question.fromJson({
          ...entry,
          'source': QuestionSource.seed.id,
        });

        // Content-derived ids mean the same question in two packs is the same
        // id. First pack wins, so a later pack cannot silently restate an
        // earlier one.
        if (question.id.isEmpty || !seenIds.add(question.id)) continue;
        questions.add(question);
      }
    }

    return questions;
  }
}

/// Decodes one pack file into raw entries.
///
/// Top-level and returning plain maps so it can run through [compute].
/// Tolerates both the `{formatVersion, questions: [...]}` envelope and a bare
/// array, because the admin CLI's hand-written content files are bare arrays
/// and there is no reason to make them special.
List<Map<String, dynamic>> _decodePack(String raw) {
  final decoded = jsonDecode(raw);

  final list = switch (decoded) {
    final List<dynamic> l => l,
    final Map<String, dynamic> m =>
      m['questions'] as List<dynamic>? ?? const [],
    _ => const <dynamic>[],
  };

  return list.whereType<Map<String, dynamic>>().toList(growable: false);
}
